package formatter_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/werf/wormatter/pkg/formatter"
)

func TestFormatter(t *testing.T) {
	testdataDir := "testdata"

	inputPath := filepath.Join(testdataDir, "input.go")
	expectedPath := filepath.Join(testdataDir, "expected.go")
	actualPath := filepath.Join(testdataDir, "actual.go")

	inputBytes, err := os.ReadFile(inputPath)
	if err != nil {
		t.Fatalf("failed to read input file: %v", err)
	}

	if err := os.WriteFile(actualPath, inputBytes, 0o644); err != nil {
		t.Fatalf("failed to write actual file: %v", err)
	}
	defer os.Remove(actualPath)

	if err := formatter.FormatFile(actualPath, formatter.Options{}); err != nil {
		t.Fatalf("formatter failed: %v", err)
	}

	actualBytes, err := os.ReadFile(actualPath)
	if err != nil {
		t.Fatalf("failed to read actual file: %v", err)
	}

	expectedBytes, err := os.ReadFile(expectedPath)
	if err != nil {
		t.Fatalf("failed to read expected file: %v", err)
	}

	if string(actualBytes) != string(expectedBytes) {
		t.Errorf("formatted output does not match expected.\n\nActual:\n%s\n\nExpected:\n%s", actualBytes, expectedBytes)
	}
}

func TestFormatterIdempotent(t *testing.T) {
	testdataDir := "testdata"
	expectedPath := filepath.Join(testdataDir, "expected.go")
	actualPath := filepath.Join(testdataDir, "idempotent.go")

	expectedBytes, err := os.ReadFile(expectedPath)
	if err != nil {
		t.Fatalf("failed to read expected file: %v", err)
	}

	if err := os.WriteFile(actualPath, expectedBytes, 0o644); err != nil {
		t.Fatalf("failed to write actual file: %v", err)
	}
	defer os.Remove(actualPath)

	if err := formatter.FormatFile(actualPath, formatter.Options{}); err != nil {
		t.Fatalf("formatter failed: %v", err)
	}

	actualBytes, err := os.ReadFile(actualPath)
	if err != nil {
		t.Fatalf("failed to read actual file: %v", err)
	}

	if string(actualBytes) != string(expectedBytes) {
		t.Errorf("formatter is not idempotent: running twice produces different output")
	}
}

func TestFormatterCheckMode(t *testing.T) {
	testdataDir := "testdata"
	expectedPath := filepath.Join(testdataDir, "expected.go")
	actualPath := filepath.Join(testdataDir, "check.go")

	unformattedContent := `package main

func main() {}
var x = 1
const y = 2
`

	if err := os.WriteFile(actualPath, []byte(unformattedContent), 0o644); err != nil {
		t.Fatalf("failed to write actual file: %v", err)
	}
	defer os.Remove(actualPath)

	err := formatter.FormatFile(actualPath, formatter.Options{CheckOnly: true})
	if err == nil {
		t.Error("expected error for unformatted file in check mode")
	}

	contentAfterCheck, _ := os.ReadFile(actualPath)
	if string(contentAfterCheck) != unformattedContent {
		t.Error("check mode should not modify the file")
	}

	expectedBytes, err := os.ReadFile(expectedPath)
	if err != nil {
		t.Fatalf("failed to read expected file: %v", err)
	}

	if err := os.WriteFile(actualPath, expectedBytes, 0o644); err != nil {
		t.Fatalf("failed to write actual file: %v", err)
	}

	err = formatter.FormatFile(actualPath, formatter.Options{CheckOnly: true})
	if err != nil {
		t.Errorf("expected no error for formatted file in check mode, got: %v", err)
	}
}

func TestFormatterGeneratedFile(t *testing.T) {
	actualPath := "testdata/generated.go"
	content := `// Code generated by some tool. DO NOT EDIT.
package main

func main() {}
var x=1
`

	if err := os.WriteFile(actualPath, []byte(content), 0o644); err != nil {
		t.Fatalf("failed to write generated file: %v", err)
	}
	defer os.Remove(actualPath)

	if err := formatter.FormatFile(actualPath, formatter.Options{}); err != nil {
		t.Fatalf("formatter failed: %v", err)
	}

	actualBytes, err := os.ReadFile(actualPath)
	if err != nil {
		t.Fatalf("failed to read actual file: %v", err)
	}

	if string(actualBytes) != content {
		t.Error("generated file should not be modified")
	}
}

func TestFormatterExcludePattern(t *testing.T) {
	actualPath := "testdata/excluded.go"
	content := `package main

func main() {}
var x = 1
`

	if err := os.WriteFile(actualPath, []byte(content), 0o644); err != nil {
		t.Fatalf("failed to write file: %v", err)
	}
	defer os.Remove(actualPath)

	err := formatter.FormatFile(actualPath, formatter.Options{
		ExcludePatterns: []string{"excluded.go"},
	})
	if err != nil {
		t.Fatalf("formatter failed: %v", err)
	}

	actualBytes, err := os.ReadFile(actualPath)
	if err != nil {
		t.Fatalf("failed to read actual file: %v", err)
	}

	if string(actualBytes) != content {
		t.Error("excluded file should not be modified")
	}
}
